openapi: 3.0.0
info:
  title: Trazzle API
  description: 트래즐 서비스 API
  version: '1.0.0'
  contact:
    name: 서동성
    email: sds901234@naver.com
tags: []
servers: []

paths:
  /api/users:
    get:
      $ref: './paths/api/users/get.yaml'

  /api/users/sign-out:
    get:
      $ref: './paths/api/users/sign-out/get.yaml'

  /api/users/sign-in/kakao:
    post:
        $ref: './paths/api/users/sign-in/kakao/post.yaml'
  /api/users/sign-in/apple:
    post:
      $ref: './paths/api/users/sign-in/apple/post.yaml'

  /api/users/sign-in/google:
    post:
      $ref: './paths/api/users/sign-in/google/post.yaml'
  /api/users/sign-in/account:
    post:
      $ref: './paths/api/users/sign-in/account/post.yaml'
  /api/users/profile:
    patch:
      $ref: './paths/api/users/profile/patch.yaml'
  /api/users/token:
    patch:
      $ref: './paths/api/users/token/patch.yaml'
  /api/users/statistics:
    get:
      $ref: './paths/api/users/statistics/get.yaml'




  /api/travel-notes:
    post:
      $ref: './paths/api/travel-notes/post.yaml'
    get:
      $ref: './paths/api/travel-notes/get.yaml'
  /api/travel-notes/{id}:
    get:
      $ref: './paths/api/travel-notes/{id}/get.yaml'
    put:
      $ref: './paths/api/travel-notes/{id}/put.yaml'
    delete:
      $ref: './paths/api/travel-notes/{id}/delete.yaml'
  /api/countries:
    get:
      $ref: './paths/api/countries/get.yaml'
  /api/cities:
    get:
      $ref: './paths/api/cities/get.yaml'
  /api/magnets:
    get:
      $ref: './paths/api/magnets/get.yaml'
  /terms/personal-info:
    get:
      operationId: TermsController_getTermsOfPersonalInfo
      summary: 개인정보 처리방침 약관 조회
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_5
        - 이용약관
  /terms/service:
    get:
      operationId: TermsController_getTermsOfService
      summary: 서비스 이용 약관 조회
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_5
  /api/back-office/countries:
    post:
      $ref: './paths/api/back-office/countries/post.yaml'
  /api/back-office/countries/{code}:
    get:
      $ref: './paths/api/back-office/countries/{code}/get.yaml'
    patch:
     $ref: './paths/api/back-office/countries/{code}/patch.yaml'
  /api/back-office/cities:
    post:
      $ref: './paths/api/back-office/cities/post.yaml'
    patch:
      $ref: './paths/api/back-office/cities/patch.yaml'

  /api/back-office/admins:
    post:
      $ref: './paths/api/back-office/admins/post.yaml'
    get:
      $ref: './paths/api/back-office/admins/get.yaml'
    patch:
      $ref: './paths/api/back-office/admins/patch.yaml'
    delete:
      $ref: './paths/api/back-office/admins/delete.yaml'
  /api/back-office/admins/{id}:
    get:
      $ref: './paths/api/back-office/admins/{id}/get.yaml'
  /api/back-office/magnets:
    post:
      $ref: './paths/api/back-office/magnets/post.yaml'
    patch:
      $ref: './paths/api/back-office/magnets/patch.yaml'
    delete:
      $ref: './paths/api/back-office/magnets/delete.yaml'

components:
  $ref: './components/index.yaml'
